### ISSUE TITLE
remove IIIF manifest generation from publish step

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor-services#109]
See https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/models/publishable.rb#L66

For deployment, we need to:
- [x] Merge https://github.com/sul-dlss/dor-services/pull/128 for the public XML generation
- [x] Cut a 4.x dor-services release (`4.23.0`)
- [x] Deploy new dor-services 4.x into dor-services-app
- [x] Deploy new dor-services 4.x into common accessioning
- [ ] Clean up manifests in PURL document_store afterwards
- [x] Merge https://github.com/sul-dlss/dor-services/pull/157 for 5.x forward port of functionality

**Comment by drh-stanford** [comment]
PR https://github.com/sul-dlss/dor-services/pull/114 is merged now.

**Comment by atz** [comment]
`dor-services-app` now on `5.27.0`

**Comment by jcoyne** [comment]
I don't think we know what we need to do here, so closing.
