### ISSUE TITLE
add support for keep-alive connections

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor-services#123]
rubydora and dor-workflow-service do not support keep alive connections as they both use the rest-client gem

**Comment by atz** [comment]
dor-workflow-service now updated to support it.  rubydora outstanding.

**Comment by atz** [comment]
Do we think we are going to be able to update rubydora?  Might be out of scope.

**Comment by drh-stanford** [comment]
I created an issue on the Rubydora repo, and got a "submit a PR" response. So, we'll have to code it up ourselves. It would likely be a major performance improvement.

**Comment by atz** [comment]
https://github.com/projecthydra/rubydora/issues/97

**Comment by atz** [comment]
Status?
