### ISSUE TITLE
Cache XSLT objects, save file read and parsing costs

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-services#135]
For example, cache Nokogiri::XSLT in `lib/dor/models/describable.rb`.

**Comment by atz** [comment]
See also: the monkey-patch `prettify` in `lib/dor/utils/ng_tidy.rb`.  Used by argo, but not referenced in dor-services or tested.

**Comment by drh-stanford** [comment]
For some earlier XML cleanup issues, I added the `nokogiri-pretty` gem to `dor-services` which adds a `.human` method to `Nokogiri::XML::Node`. Argo could use that instead of our custom code in `ng_tidy`.
