### ISSUE TITLE
Dor.find fails to load_instance for exceptions in Dor.find_all

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/dor-services#147]
https://github.com/sul-dlss/dor-services/blob/develop/lib/dor-services.rb#L30-L61

If `Dor.find_all` raises exceptions that are not handled in that method, the `Dor.find` method will not try `Dor.load_instance`.  There are various levels of exception handling required for HTTP, Solr, and Fedora.

**Comment by darrenleeweber** [comment]
While developing Argo, an exception was raised from Fedora that is not handled in Dor.  For `Dor.find junk`, the Dor.find calls `Dor.find_all` and it first tries Solr and then Fedora.  With no Solr data and an internal 500 error on Fedora, Dor.find crashes.

The Dor details are in
https://github.com/sul-dlss/dor-services/blob/develop/lib/dor-services.rb#L30-L61

So the `Dor.find_all` throws an exception and it doesn’t try the `|| load_instance` on
https://github.com/sul-dlss/dor-services/blob/develop/lib/dor-services.rb#L37

If it tried the `load_instance`, then it might return `nil`, details in
https://github.com/sul-dlss/dor-services/blob/develop/lib/dor-services.rb#L17-L28

Note that the exception returned in the `Dor.find junk` is
```Rubydora::FedoraInvalidRequest: See logger for details
from /home/dlweber/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rubydora-1.6.5/lib/rubydora/rest_api_client.rb:26:in `block (2 levels) in <module:RestApiClient>'
```

This is likely the source of the problem in https://github.com/sul-dlss/argo/pull/466

**Comment by atz** [comment]
A bad ID is a legitimate source of exception, since it suggests a fundamental inconsistency of the system.  `find_all` is deprecated, so this is no longer an issue.  `find` **only** does `load_instance` now.
