### ISSUE TITLE
Why is modsulator a dependency of dor-services?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dor-services#180]
I don't see where modsulator is used in the dor-services code; why is it bundled into dor-services?

**Comment by LynnMcRae** [comment]
Modsulator turns rows and columns (CSV or XLS) into MODS XML.  It is just one step to getting a spreadsheet loaded into DOR.  Modsulator itself should have no DOR dependencies. This may be an artifact of the original offline version of the facility when the conversion was bound in with the loading?

**Comment by cbeer** [comment]
Ok, it turns out `dor-services` is using `modsulator` for some XML normalization routines.

**Comment by LynnMcRae** [comment]
are you sure it's modsulator? (a rhetorical question) ... There's an XML normalizer that modsulator uses that should be available separately.  See https://consul.stanford.edu/display/chimera/MODS+bulk+loading 

If they are intertwined, it would be good to separate them.

**Comment by cbeer** [comment]
Yes, it's all wrapped up in modsulator's normalizer.

**Comment by drh-stanford** [comment]
We're only using a subset of modsulator for normalizing the `rightsMetadata`. I think it'd be fine to create a common gem that only has the basic XML normalization functions. See https://github.com/sul-dlss/argo/issues/71

**Comment by atz** [comment]
Resolved by #344
