### ISSUE TITLE
The relatedItem generated by the system to reflect the relationship isContituentOf needs to dereference the object with the MODS title instead of the dc label

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/dor-services#203]
@blalbrit @LynnMcRae

**Comment by LynnMcRae** [comment]
Example of a bad reference please.  This should be fixed by https://github.com/sul-dlss/argo/issues/647. We will reindex virtual object children when this goes in.

**Comment by lmcglohon** [comment]
Bad reference is the second relatedItem with displayLabel="Appears in" - https://purl.stanford.edu/yr145dc7638.mods:

<relatedItem type="host" displayLabel="Appears in">
<titleInfo>
<title>Rumsey Atlas 2542</title>
</titleInfo>
<location>
<url>http://purl.stanford.edu/hj097bm8879</url>
</location>
</relatedItem>
