### ISSUE TITLE
document ssh key dependency to lyberservices-prod on list_files method call

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/dor-services#205]
When including this gem and using the list_files method call, the application's user requires a key to be able to SSH to `lyberservices-prod` as user `lyberadmin` - it would be great to document that dependency

**Comment by atz** [comment]
In `README`, presumably.

**Comment by cbeer** [comment]
Are `#list_files` and `#get_file` good candidates for exposing as an HTTP API in dor-services-app? I believe this would allow us to remove SSH keys from Argo. @LynnMcRae?

**Comment by LynnMcRae** [comment]
I actually thought Argo had the dor workspace mounted and could access it directly to show users if a file copy was in the workspace and offer it to them as a link if so. Regardless, to answer your question, a Web Services path would be swell if we are better isolating services for consistent access. It would also open up some scripted use of the workspace for some file manipulations we have to do manually with direct login. Keep in mind we have a small list of content management needs we want to put into Argo, like file replacement, adding a resource, renaming a file.  I would love to see this realized though web services as well if this makes all that more feasible.

**Comment by atz** [comment]
`Contentable` (including all `Dor::Item`s) uses SFTP, but I agree only `digital_stacks_service` seems to use SSH (in addition to SFTP).

**Comment by jcoyne** [comment]
This will be deprecated in 6.1 and removed in 7.0.  We already have these functions in dor-services-client (https://github.com/sul-dlss/dor-services-client/blob/master/lib/dor/services/client/files.rb) which talks to dor-services-app.  Argo is now using dor-services client to make these requests.
