### ISSUE TITLE
Indexing efficiency in related item lookups

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/dor-services#208]
When indexing any object, we lookup the name of the governing APO and the name of a collection, if any. We do this to populate usable facets and optimize the display of this information in  Argo. Apparently each lookup current involves a full instantiation of the remote object just to get the title out of descMetadata.  We believe this is what is behind these numbers shared by Erin:

> I was looking at the access log file on dor to see what it was requests it was receiving right before tomcat fell over
> 
> from `dor-indexing-app-prod-a`:
>    2313 /fedora/objects/druid:xh235dd9059/datastreams/workflows?format=xml
>    2314 /fedora/objects/druid:xh235dd9059/datastreams?format=xml
>    2314 /fedora/objects/druid:xh235dd9059/datastreams/RELS-EXT?format=xml
>    2314 /fedora/objects/druid:xh235dd9059?format=xml
>    2316 /fedora/objects/druid:xh235dd9059/datastreams/RELS-EXT/content
> 
> the first column is the amount of requests to that endpoint between 10:10am and 10:19am

This means some 12,000 Fedora calls in 9 minutes to, in this case, the Rumsey Maps Collection object to get the title.  Full object reconstruction certainly isn't needed for a title lookup.  Just one call for the MODS would do: /fedora/objects/druid:xh235dd9059/datastreams/descMetadata/content, but even better would likely to a call to solr where the title is more directly available, and far more efficiently. Some caching of answers could also be considered, but eliminating calls to a heavyweight object alone could be a substantial improvement. 

Needs some confirmation and further analysis.  We do title lookups for publish as well, to create both a collection and "Appears in" relatedItem. They would benefit from the same optimization, though we want to know when a subtitle needs to be included in the lookup.

**Comment by cbeer** [comment]
Fixed in #242. 

> Some caching of answers could also be considered, but eliminating calls to a heavyweight object alone could be a substantial improvement.

Is under consideration at https://github.com/sul-dlss/dor_indexing_app/wiki/Possible-Performance-Improvements
