### ISSUE TITLE
Empty admin tag causes indexing failure

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/dor-services#212]
Some of the objects that failed reindexing had an empty <tag/> element in identityMetadata which prevented the object from being indexed. The affected objects have been identified and are being fixed, so nothing urgent, just an indexing vulnerability that bites us occasionally.

**Comment by atz** [comment]
@LynnMcRae What do you propose should be done about it?  

- We can suppress the failure in one place and continue attempting to index, but possibly just fail later in another place.  
- We can try to make the whole indexing operation resilient to such bad data, but then have a bad **index**
- We can try to index the fact that the bad data exists
- Or we can rely on similar failures to prompt us to cleanup the bad data, as done here.

**Comment by LynnMcRae** [comment]
The general problem with doing nothing and reacting to such indexing failures is they they are silent so there could be long lags or misunderstanding about other changes to the object that aren't getting reflected in searches. Given the expected life span on this XML schema, I'd like to state the requirement to be we index the tag values that are present, not simply all instances of the `<tag>` element. I don't remember if we thought we had an isolated cleanup of older records or if there's an ongoing issue with empty tags being created today.

**Comment by jcoyne** [comment]
Closing because this is very stale.  Please reopen if still a problem.
