### ISSUE TITLE
Indexing errors - Solr 6.1 rejecting workflow datestamps

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/dor-services#214]
The indexing of workflow datestamps had a formatting error that seems to have been ignored to date, but which is now causing indexing failures. It was taking a time-adjusted datstamp like 2016-07-05T12:34:56.789-0700 and appending the value with a "Z". The resulting hybrid "...-0700Z" is not valid.

**Comment by jmartin-sul** [comment]
fixed.  dor-services consumers are being upgraded.

if we backport this to 4.x, i'd be in favor of just reimplimenting by hand.  the change is straight-forward, and there was enough code cleanup and reformatting in the 4 to 5 upgrade that i'd be wary of conflicts if we were to cherry pick the commits from 5.x.
