### ISSUE TITLE
Publish should not leave altered <release> tags in identityMetadata

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/dor-services#226]
A history of release activity is recorded in identityMetadata, a trail of true's and false's, when and by whom.  Publish determines the current release state of an item either from local release information or as inherited from a collection.  This answer is placed in a \<releaseData> container at the end of the Public XML.

Publish seem to also be replacing the \<release> tag in identityMetadata with the same or similar information. This should not be there ... the \<release> tag should simply not appear in identityMetadata in the Public XML. 

This was fixed at one time, by https://jirasul.stanford.edu/jira/browse/STNFRDSYNC-128, but still seems to be happening.  Test case = https://purl-test.stanford.edu/bb104kn2363.xml

**Comment by peetucket** [comment]
interesting, the code was very deliberately adding the same data that goes into <releaseData> back into <identityMetadata>.  I've removed this code and added tests for it.  It is now part of this PR:  https://github.com/sul-dlss/dor-services/pull/235
