### ISSUE TITLE
to_solr should case normalize release target ids for facet

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/dor-services#227]
Target names for discovery release are case insensitive, value entered should be case normalized for the facet to prevent, e.g., the Searchworks split here:
![screen shot 2016-08-30 at 12 16 20 pm](https://cloud.githubusercontent.com/assets/1824732/18103522/d9219964-6eab-11e6-8187-877e899a7a4f.png)

All lower case would be fine.

**Comment by atz** [comment]
Why is this not considered 4 (or 126) flawed pieces of data?  Isn't the release target is supposed to be a uniquely keyed value?

**Comment by LynnMcRae** [comment]
Setting this aside as values from are constrained by the interface
