### ISSUE TITLE
releasable adds two extraneous attributes to the release tag in identityMetadata

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/dor-services#229]
When you release an object, you get a statement like this;

```
<release displayType="file" release="true" to="SearchWorks" what="self" when="2016-09-16T19:28:05Z" who="pjreed">true</release>
```
Both the **displayType="file"** and **release="true"** attributes are incorrect, one deprecated, one just wrong.

**Comment by peetucket** [comment]
so both displayType and release=true attributes should not be there?  the value of the release is the value for the tag (and not an attribute?)

**Comment by LynnMcRae** [comment]
yes, those two attributes should go. The value of the tag is the real payload.

**Comment by peetucket** [comment]
I am seeing some examples/tests in the code where there is a "tag" attribute as well.  Should this be allowed when creating a release tag?  Or is it deprecated as well and should I strip it if passed in?  

```<release tag="Fitch : Batch2" what="self" to="Searchworks" who="petucket" when="2016-09-27T19:03:07Z">true</release>```

**Comment by LynnMcRae** [comment]
ah yes, "tag" is deprecated as well. You don't have to accommodate it, just make it illegal or ignored like other non-defined things.
