### ISSUE TITLE
Argo/DOR indexing fails if a MODS language code lacks an authority attribute

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/dor-services#230]
MODS language codes should look something like this:

```
<languageTerm type="code" authority="iso639-2b">eng</languageTerm>
```

The authority attribute guides in the translation of a code into a value.  If missing, we get an indexing error trying to create the equivalent of a Searchworks language facet:

```
ERROR [2016-09-16 12:28:22] (27702)  :: #<NoMethodError: undefined method `match' for []:Array>
/path/shared/bundle/ruby/2.2.0/gems/stanford-mods-1.5.3/lib/stanford-mods/sea
rchworks.rb:19:in `block (2 levels) in sw_language_facet'
```

Instead we should just index the raw value for visibility.

This has been rare, and the data should be fixed, but it should not prevent indexing the value. It is an identified error in the specs for a Collection Profile report.

**Comment by peetucket** [comment]
Can you provide a specific druid example of an object with this error?  The underlying exception is coming from stanford-mods so it likely can be corrected there too.

**Comment by LynnMcRae** [comment]
I'll create one in stage since we're fixing the cases in prod!

**Comment by LynnMcRae** [comment]
https://argo-stage.stanford.edu/catalog/druid:qv863zk5546 has a damaged <languageTerm> tag and will no longer index.

**Comment by peetucket** [comment]
I looked into this and found that the latest version of stanford-mods (2.2.1) already deals with this by ignoring the authority.  sw-indexer currently uses the latest stanford-mods and should have no issues.  dor-services is still using stanford-mods 1.5.3 and probably just needs to be updated (and/or Argo).  I added some tests for this behavior to a forthcoming stanford-mods 2.2.2 release (which also deals with sul-dlss/discovery-dispatcher#122)

**Comment by jmartin-sul** [comment]
dor-services currently pins stanford-mods because of an incompatibility with stanford-mods v1.5.4+.  IIRC, it didn't seem like it'd be a terrible incompatibility to fix, but required enough thought/effort that we put it off when it came up (it appears the version was pinned in feb of this year, which would've been in the final push to get argo 3 out the door).

https://github.com/sul-dlss/dor-services/blob/master/dor-services.gemspec#L46-L47
``` ruby
  s.add_dependency 'stanford-mods', '= 1.5.3'  # v1.5.4 changes what sw_genre returns, which breaks test expectations.
# TODO: (stanford-mods) figure out how to keep argo indexed counterparts of searchworks fields in sync w/ current SW behavior.
```

**Comment by LynnMcRae** [comment]
Here's where this currently stands ...

Ticket https://github.com/sul-dlss/argo/issues/642 suggests we index all MODS \<genre> values and rename the facet as MODS Genre. It would mean we would **not** use the Stanford-MODS call that presents a filtered Genre list but rather a call which I assume exists to get the real values from the \<genre> tag. 

Ticket https://github.com/sul-dlss/argo/issues/644 suggests we unpin the dependency and create a valid SW Genre facet, with tests revised to check for the valid set of values (per https://github.com/sul-dlss/stanford-mods/issues/66) -- this is a set of manufactured values derived from a subset of actual \<genre> values. We would have to reindex all objects for this.

Or we could do both as each could have value in the Collection Profile. I will confer with Ben and others to see where we stand on this.

**Comment by LynnMcRae** [comment]
Note my comment above relates to the reasons Argo is pinned to an older version of DOR Services, not about the issue at the heart of this ticket.  But it is a blocker. I'll take the information and work the related tickets to see if we can identify the desired course of action.

**Comment by jmartin-sul** [comment]
@LynnMcRae:  not sure i understand the above, argo should be on the latest version of dor-services:
https://github.com/sul-dlss/argo/blob/v3.5.0/Gemfile.lock#L192
https://github.com/sul-dlss/dor-services/compare/v5.10.1...master

**Comment by LynnMcRae** [comment]
sorry, it's the stanford-mods version that's pinned, as used in this case by the dor services to_solr method.

**Comment by LynnMcRae** [comment]
Ticket https://github.com/sul-dlss/argo/issues/644 will allow us to unpin the version of stanford-mods involved in indexing, moving to the latest version and eliminating this issue. We should leave this ticket open to validate the fix once the change is made.

**Comment by cbeer** [comment]
It seems like this was addressed. stanford-mods seems not to be pinned, and we recently reindexed all objects successfully.
