### ISSUE TITLE
solr_name is deprecated

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-services#28]
As used in `add_solr_value()`:
https://github.com/sul-dlss/dor-services/blob/master/lib/dor/utils/solr_doc_helper.rb

``` ruby
  def add_solr_value(solr_doc, field_name, value, field_type = :default, index_types = [:searchable])
    index_types.each { |index_type|
      ::Solrizer::Extractor.insert_solr_field_value(solr_doc, ::ActiveFedora::SolrService.solr_name(field_name, field_type, index_type), value)
    }
  end
```

Warning now issued here:
https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/solr_service.rb#L87

```
SolrService.solr_name is deprecated. Use SolrQueryBuilder.solr_name instead. This will be removed in active-fedora 10.0
```

This affects all our to_solr calls, basically.

**Comment by cbeer** [comment]
Seems like this has been done.
