### ISSUE TITLE
License facet contains a blank entry

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/dor-services#284]
![screen shot 2016-11-28 at 1 25 16 pm](https://cloud.githubusercontent.com/assets/1824732/20687668/49a402fa-b572-11e6-9576-a744a7400d60.png)

You can get a search result of these items with https://argo.stanford.edu/catalog?f%5Buse_license_machine_ssi%5D%5B%5D=

These result from partially declared licenses in many objects

```
<rightsMetadata>
      :
  <use>
    <human type="creativeCommons"/>
    <machine type="creativeCommons"/>
  </use>
```

It also seems to come from objects that lack rightsMetadata altogether, e.g., druid:bb001bb1008

In both cases there should be a "No License" entry in the Empty Fields facet.

**Comment by drh-stanford** [comment]
From @cbeer 

> i’ve looked into the blank license value. i believe previously we were unconditionally stripping blank values out of the solr document when serializing it for solr, and that behavior changed in rsolr 2.x to put the onus on the indexing code to correctly prepare the document instead. i think we should treat it either as bad data or write explicit logic for the various cases spot-checking, i see a lot of `rightsMetadata` documents with `<machine type="creativeCommons"/>`  instead of e.g. `<machine type="creativeCommons">by-nc</machine>` and separately, i think there’s a bug indexing documents without rightsmetadata here: https://github.com/sul-dlss/dor-services/blob/ea4bd171509cf2eb1fb30e1a11ed6b4d14fa3c8a/lib/dor/datastreams/rights_metadata_ds.rb#L206

> we’re explicitly returning an empty string, and probably mean to return nil

**Comment by LynnMcRae** [comment]
unfortunately somehow the process of creating XML in multiple apps (through active fedora??) leaves lots of empty tags in lots of metadata, sloppy but generally not visible except perhaps in this case where the attribute of “type=”creativeCommons” makes it appear to have more substance (it doesn’t). All Revs objects (423,000) are in this state I think, but many thousands others are scattered throughout. We've made a concerted effort to do MODS cleanup; rightsMetadata may be the only other problematic datastream in this manner.
