### ISSUE TITLE
Assembleable module not included in collection or apo objects

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services#317]
If you have content in an APO or Collection object and want to accession that content using the assembly robots, it won't work, since the assembly robots make use the "Assembleable" module (via dor-services-app) to initialize the work space.  This module is only included in the item model.

The assembly robots will now only attempt to initialize the work space for items (see https://github.com/sul-dlss/assembly/pull/61), but if in the future we need to run APOs and Collections through assembly with content, we would need to:

1. include Assembleable in collections and APOs
2. modify assembly so that the dor-services-app call to initialize the work space once again occurs for all object items (and is not restricted to just images)

**Comment by atz** [comment]
I believe that not having content in an APO is intentional, currently.  That is to say, the way we have modeled things has intentionally made `Item` the class for holding content.  Does that match what you're seeing?

**Comment by LynnMcRae** [comment]
There is no intention to have APOs bear content (they once did in an early model where they housed their agreements; but agreements got split to separate objects for sharing). Collections still in theory might get content, for something like a thumb perhaps, but uses cases around that moved over to exhibits and we have no driving use case for DOR collections with content at the moment, so little risk to assume they won't bear content prior to SDR3.  Workflow objects of course will not have content, and agreements by definition must and do.
