### ISSUE TITLE
sourceID duplication check is not enforcing unique sourceIDs

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/dor-services#341]
From the user point of view:
- when registering objects in Argo, the sourceID field is supposed to be unique
- in the past, Argo would fail to register an object if its sourceID already existed
- currently, duplicate sourceIDs are being allowed
![screenshot 2018-02-26 12 46 43](https://user-images.githubusercontent.com/796990/37226650-85e7aa46-238f-11e8-8415-d8090d4b46e1.png)
![screenshot 2018-02-26 12 48 57](https://user-images.githubusercontent.com/796990/37226660-8c570c50-238f-11e8-8bde-69a3352e502f.png)

We believe this https://github.com/sul-dlss/dor-services/blob/ccfe71b5d15305eaf3ac8fd8c64f6d4376d4f7ad/lib/dor/services/registration_service.rb#L23-L32 is the code where the failure might be happening (though this is just a suggestion and should be confirmed)

**Comment by jcoyne** [comment]
Closing because this is very stale.  Please reopen if still a problem.
