### ISSUE TITLE
Deprecate copy_file_resources (and related code) 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services#399]

**Comment by jcoyne** [comment]
Does dor-services-app use dor-services to provide these services?

**Comment by mjgiarlo** [comment]
@jcoyne 

> Does dor-services-app use dor-services to provide these services?

It doesn't appear so based on what you linked above: https://github.com/sul-dlss/dor-services-app/blob/master/app/controllers/content_controller.rb

Is there something I may be missing?

**Comment by mjgiarlo** [comment]
@jcoyne It also appears that Argo (after https://github.com/sul-dlss/argo/pull/1287 was merged) now does the `list_files` part of this. My read is that we have work left to do on `copy_file_resources`. Is that your understanding as well?

**Comment by mjgiarlo** [comment]
@jcoyne 	as far as I can tell nothing in the sul-dlss org invokes `copy_file_resources`.

**Comment by mjgiarlo** [comment]
Chatted with @jcoyne and given :point_up: we decided to re-cast this issue as one around deprecation of unused code in dor-services.
