### ISSUE TITLE
Do we still need to build datastreams from files?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services#428]
https://github.com/sul-dlss/dor-services/blob/master/lib/dor/models/concerns/processable.rb#L69-L79

@peetucket @cbeer @blalbrit do you have any insight into when and why we would do this?

**Comment by peetucket** [comment]
The `ContentMetadata` and `DescMetadata` robot are allowed to build the datastream by reading a file from the /dor/workspace that matches the datastream name.  This allows assembly or pre-assembly to prebuild the datastreams from templates or using other means (like the `assembly-objectfile` gem) and then have those datastreams picked up and added to the object during `accessionWF`.

**Comment by jcoyne** [comment]
@peetucket is it the intention that Argo would also kick off that behavior here? https://github.com/sul-dlss/argo/blob/4b4f82f913af1da5e367a8e145f45cfa4527a4d2/app/controllers/items_controller.rb#L551

**Comment by peetucket** [comment]
I am not 100% sure, though a code search looks like that method is connected to a "Refresh MODs" button that I've never used.  Given the fact that method does nothing else, I assume its intentional.  Perhaps that was used when someone hand-edited the file on disk and wanted it reloaded to the datastream?  Seems like an odd use case though and not one that I've ever used.  Really a question for Ben.

**Comment by jcoyne** [comment]
Okay, thanks for the help @peetucket I've encoded a bunch of this in #429

**Comment by blalbrit** [comment]
@peetucket @jcoyne - Refresh MODs should make a call to the catalog service (if the object is associated with a catkey), perform the marc2mods transform, and load the new metadata into the descMetadata stream, overwriting everything  that was in there before.

Refresh MODS is used pretty regularly by the metadata unit & some stakeholders as a manual way of keeping the MARC and MODS records in sync, or of adding a catkey and updating the mods after the fact. Both tasks could be handled more elegantly.

Other than that use-case, I'm not really sure how this method is (would be) used in the current environment.
