### ISSUE TITLE
version_metadata_ds redefines current_version_id

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-services#43]
See here:
https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/datastreams/version_metadata_ds.rb#L111
and
https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/datastreams/version_metadata_ds.rb#L155

Pick one.

**Comment by atz** [comment]
@wmene ?

**Comment by wmene** [comment]
Sorry, I didn't have a watch on this repo, so I wasn't getting notices.

Choose the first one, since it handles the nil case
