### ISSUE TITLE
ContentMetadataDS has bogus and inconsistent methods, fake tests

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-services#61]
Like this gem:
```ruby
    def move_resource resource_name, new_position
      xml=self.ng_xml
      file_node=xml.search('//resource[@id=\''+resource_name+'\']')
      if(file_node.length!=1)
        raise 'Resource not found or duplicate found.'
      end
      position=file_node.first['sequence'].to_i
      #is the resource being moved earlier in the sequence or later?
      new_position=new_position.to_i
      if new_position>position
        counter=position
        while true
          if counter == position
            break
          end
          item=xml.search('/resource[@id=\''+counter.to_s+'\']').first
          counter=counter+1
          item['sequence']=counter.to_s
        end
      else
        counter=position
        while true
          if counter == new_position
            break
          end
          item=xml.search('/resource[@id=\''+counter.to_s+'\']').first
          counter=counter-1
          item['sequence']=counter.to_s
        end
      end
    end
```

So on `new_position > position`... do nothing?  Notably, the test for this method called it, but never defined any expectation about what it wanted to result.  Just don't crash = OK!

Another head scratcher:
```ruby
    def update_resource_type resource, new_type
      xml=self.ng_xml
      resource_node=xml.search('//resource[@id=\''+resource_name+'\']')
      if(resource_node.length!=1)
        raise 'Resource not found or duplicate found.'
      end
      resource_node.first['type']=new_type
    end
```

The method receives `resource` but then uses only `resource_name`.  In fact, it should crash right?  Turns out the test named for it also defines no expectation.... and doesn't even invoke it!  

More broadly, there is confusion about when modification code should:
- write XML back to the datastream (`self.content=xml.to_s`)
- `self.save`

Does a modifying method update XML and save?  Quick survey:
- `add_file`: both
- `add_resource`: both
- `remove_resource`: both
- `remove_file`: both
- `update_attributes `: both
- `update_file`: both 
- `rename_file`: both 
- `update_resource_label`: neither
- `update_resource_type`:  neither (**invalid**)
- `move_resource`: neither (**broken**)
- `set_content_type`: sets XML only

In order to avoid 10,000 writes, I suspect the proper answer is that it should **never** call save automatically.  Don't write it until explicitly told.  After all, we are following an ActiveSupport pattern here.  But that entails making sure none of our consumers are relying on it.

**Comment by atz** [comment]
@wmene, @jmartin-sul

**Comment by jmartin-sul** [comment]
my two cents:  if we can find all of the callers of all of those methods, i'd vote for changing the methods to never save.  if it's obvious from the code surrounding a call whether an implied save is expected, we can add or not add the save call there accordingly.  if it's not clear and it'd be difficult to figure out, it seems safe to just add a save call right after the modification call, because at worst you end up doing the same thing.

**Comment by atz** [comment]
Yeah, I think that is best.  My concern is that there may be other apps besides argo that are relying on it.  @wmene can you comment on what other code might be calling content datastream methods?

**Comment by atz** [comment]
Notably, content_metadata_ds is the ONLY datastream that calls `self.save` at all.

**Comment by atz** [comment]
@rosy1280, I think this relates to problems that you conveyed early on, but that I didn't have the context at the time to link to anything.

**Comment by wmene** [comment]
@atz pre-assembly uses `add_file`, `add_resource`, and `update_file` in `add_and_update_files.rb`  https://github.com/sul-dlss/pre-assembly/blob/ae78bbfc3fb16386c6cccea050e084f473d20054/devel/add_and_update_files.rb

**Comment by rosy1280** [comment]
I also suspect that Hydrus may use this. Can't remember whether or not it does it well because -- not shockingly -- it's been a while since I've used it.

**Comment by atz** [comment]
Not seeing any in Hydrus, based on:

```
$ git grep -nP -e '(add|remove|update)_(file|resource|attributes)' -e rename_file -e 'update_resource_(label|type)' -e move_resource -e set_content_type
app/controllers/hydrus_solr_controller.rb:48:      solr.add(solr_doc, :add_attributes => {:commitWithin => 5000})
app/models/hydrus/contentable.rb:58:      :add_file_attributes => true,
lib/tasks/fixtures.rake:47:      Dor::SearchService.solr.add(solr_doc, :add_attributes => {:commitWithin => 1000})
```

Unrelated hits.

**Comment by atz** [comment]
Based on https://github.com/projecthydra/rubydora/blob/v1.6.5/lib/rubydora/datastream.rb#L179-L201

We shouldn't need to call `content_will_change!` before setting `content=` on a datastream anymore, AFAICT.  @cbeer can you confirm that?

**Comment by atz** [comment]
Some uniformity applied.  Remaining issues under #137
