### ISSUE TITLE
StatusService can report the wrong status when timestamps are the same

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services#642]
https://argo.stanford.edu/view/druid:ns087dp7149 is indexing status_ssi as "In Accessioning" rather than "Accessioned" because two steps have the same timestamp.
```
 Dor::Config.workflow.client.milestones('dor', 'druid:ns087dp7149')
=> [{:milestone=>"registered", :at=>2019-06-05 17:44:46 +0000, :version=>"1"},
 {:milestone=>"submitted", :at=>2019-06-07 12:41:18 +0000, :version=>"1"},
 {:milestone=>"described", :at=>2019-06-07 12:41:20 +0000, :version=>"1"},
 {:milestone=>"published", :at=>2019-06-07 12:42:08 +0000, :version=>"1"},
 {:milestone=>"deposited", :at=>2019-06-07 12:42:13 +0000, :version=>"1"},
 {:milestone=>"accessioned", :at=>2019-06-07 12:42:13 +0000, :version=>"1"}]
```

**Comment by caaster** [comment]
Commenting that this object is an ETD.

**Comment by peetucket** [comment]
also, this item: https://argo.stanford.edu/view/druid:ns326hb7428

PR here: #643

**Comment by vivnwong** [comment]
Ben noticed that there are still issues with Argo status reporting does not match with actual workflow status: https://argo.stanford.edu/catalog?all=true&f%5Bprocessing_status_text_ssi%5D%5B%5D=Unknown+Status

A specific example: https://argo.stanford.edu/view/druid:bm064hp654, it is in "unknown status" but it is able to be opened for modification. 

Reopen this ticket to do further investigation.

**Comment by jcoyne** [comment]
@vivnwong That sounds like a different issue, can you open a new ticket for it?
