### ISSUE TITLE
solrizer is being deprecated, should we switch off of it?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dor-services#645]
mark bussey said on https://groups.google.com/forum/#!topic/samvera-tech/T83tGB2Sypo
> The Core Components Maintenance Working Group, in accordance with the deprecation policy posted here: https://samvera.github.io/deprecation.html would like to propose deprecation of the solrizer gem. Even after deprecation this project may receive work, have releases, and can even be re-promoted into the organization – this is simply a message to future contributors that it no longer has the work going into it necessary for it to be in the Samvera github organization.
>
> The functionality previously provided by the gem has been refactored directly into the active-fedora gem which is being actively maintained. 
>
> If there are any concerns over the deprecation of solrizer, please reply to this thread. Assuming no blockers appear, it will be moved on August 1, 2019.

so, probably not super urgent, but probably something to keep an eye on?

personally, in my dor-services maintenance work, i haven't found solrizer to do much towards making the code more flexible.  when we overhauled the solr schema in 2015/2016, we weren't taking general solrizer defined types and changing the specific field suffixes for certain types, we were totally reworking which fields were indexed and what the suffixes were in general.  i can't actually recall any cases where multiple solrizer calls stayed unchanged and some underlying definition was tweaked.

because of that, i'd have no objection to just using the field names inline.  at first glance, i don't see a practical difference, other than the removal of one layer of indirection that hasn't really paid off, to my knowledge.

also, grain of salt for the above opinion, since it's been a while since my head's been in dor-services or solrizer land.

**Comment by jcoyne** [comment]
It's being deprecated, because it's no longer used by ActiveFedora 12.  We are currently stuck on ActiveFedora 8.  Solrizer is a dependency of ActiveFedora 8 and ActiveFedora 8 is the last release of ActiveFedora that supports Fedora 3.   So, this really gets to "how do we migrate off of Fedora 3?"

**Comment by jmartin-sul** [comment]
ah.  didn't realize it was also a dependency of ActiveFedora.  i was under the impression that we just used solrizer directly (e.g. `Solrizer.solr_name('title', :stored_searchable)`).

happy to close or amend this ticket in light of the ActiveFedora dependency.
