### ISSUE TITLE
fix status computation on master branch (not only in 7-2-stable)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services#647]
PR #644 (fix status computation when a lifecycle completes with exactly the same timestamp for the last steps) put a fix in the 7-2 stable branch.

it is only in the 7-2-stable branch.  This should be forward ported

(i.e.  a PR for the same change as PR #644 should be made on the master branch)

**Comment by ndushay** [comment]
This is outside the SDR fall 2019 work cycle brief, but it should be easy to do.

**Comment by jcoyne** [comment]
I think this is fixed by #643

**Comment by jcoyne** [comment]
I think this was supposed to be for #646 (rather than #644).   It was fixed in #648 (the same day this ticket was filed)
