### ISSUE TITLE
Undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services#651]
```
undefined method `+' for nil:NilClass: /home/lyberadmin/dor-utils/shared/bundle/ruby/2.5.0/gems/dor-services-6.8.0/lib/dor/datastreams/content_metadata_ds.rb:171:in `add_virtual_resource'
bin/virtual-merge:34:in `block in merge'
```

Root cause of https://github.com/sul-dlss/dor-utils/issues/17

**Comment by ndushay** [comment]
Process directly from fixing this to sul-dlss/dor-utils#17 Do not pass go.  Do not collect $200.  :-)

Actually, it would be awesome to at least put a note in sul-dlss/dor-utils#17 that this is fixed; if possible, try running the virtual-merge script and check logs and results to see if it worked ...

**Comment by ndushay** [comment]
confirmed that the fix works.
