### ISSUE TITLE
move virtual-merge method out of dor-services

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services#652]
~~Currently virtual-merge is a script in dor-utils;  we intend to migrate it to argo (see https://github.com/sul-dlss/dor-utils/issues/66).~~

possibly blocked by sul-dlss/argo#1458 ????  See comment below.

- code for add_virtual_resource method should be moved to bulk activejob location in argo  OR  to ? dor-services-app ?
  - from in content_metadata_ds (https://github.com/sul-dlss/dor-services/blob/v6.8.0/lib/dor/datastreams/content_metadata_ds.rb#L161-L184
  - the virtual-merge is the only consumer of this code.

- don't forget to migrate the test code.

**Comment by ndushay** [comment]
@jcoyne I am assigning this to you, as recent PRs in dor-services-app and dor-services-client imply I am maybe not even asking the right question with this ticket, and you already have work in progress to "do the appropriate thing" re: where this logic should live.   

My main concern when writing this ticket was "if this code is used in one place ... then should it live where it is used?"  Like models and concerns formerly in dor-services.   

Perhaps you can just drop an explanation here in the ticket and then close it.

**Comment by jcoyne** [comment]
@ndushay I agree that this is a good proposal for a refactor.  My only qualms is that it doesn't *need* to be done right now and it doesn't need to be done by me.  I'd prefer we get the virtual-merge API working in a nominal way, and then refactor to make it clean.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> @ndushay I agree that this is a good proposal for a refactor. My only qualms is that it doesn't _need_ to be done right now and it doesn't need to be done by me. I'd prefer we get the virtual-merge API working in a nominal way, and then refactor to make it clean.

This sounds sensible to me, and in my judgment we are generally good about making time later on to handle small refactorings such as this, particularly when it reduces duplication and confusion.

**Comment by ndushay** [comment]
I'm closing this per infradev meeting today.
